name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  release-drafter:
    name: Release Drafter
    runs-on: ubuntu-22.04
    steps:
      - name: Publish Release
        uses: release-drafter/release-drafter@v5
        with:
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
